config changes

diff --git a/.config/kak/kakrc b/.config/kak/kakrc
--- a/.config/kak/kakrc
+++ b/.config/kak/kakrc
@@ -53,7 +53,10 @@ hook global WinSetOption filetype=python %{
 }
 
 hook global WinSetOption filetype=(javascript|typescript) %{
-	define-command -hidden format-eslint %{
+	define-command format-eslint -docstring %{
+	    Formats the current buffer using eslint.
+	    Respects your local project setup in eslintrc.
+	} %{
 	    evaluate-commands -draft -no-hooks -save-regs '|' %{
 	        # Select all to format
 	        execute-keys '%'
@@ -61,20 +64,27 @@ hook global WinSetOption filetype=(javascript|typescript) %{
 	        # eslint does a fix-dry-run with a json formatter which results in a JSON output to stdout that includes the fixed file.
 	        # jq then extracts the fixed file output from the JSON. -j returns the raw output without any escaping.
 	        set-register '|' %{
-	            %sh{
-	                echo "$kak_selection" | \
-	                npx eslint --format json \
-	                           --fix-dry-run \
-	                           --stdin \
-	                           --stdin-filename "$kak_buffile" | \
-	                jq -j ".[].output"
-	            }
+	            format_out="$(mktemp)"
+	            cat | \
+	            npx eslint --format json \
+	                       --fix-dry-run \
+	                       --stdin \
+	                       --stdin-filename "$kak_buffile" | \
+	            jq -j ".[].output" > "$format_out"
+	            if [ $? -eq 0 ] && [ $(wc -c < "$format_out") -gt 4 ]; then
+	                cat "$format_out"
+	            else
+	                printf 'eval -client %s %%{ fail eslint formatter returned an error %s }\n' "$kak_client" "$?" | kak -p "$kak_session"
+	                echo -n "$kak_selection"
+	            fi
+	            rm -f "$format_out"
 	        }
 
 	        # Replace all with content from register:
 	        execute-keys '|<ret>'
 	    }
 	}
+
 	set window lintcmd %{format-eslint}
     hook buffer BufWritePre .* %{format-eslint}
 }
